language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - make test
deploy:
  provider: pypi
  user:
    secure: jhWrz4rf31pQRF851dzNx9adQDKVb4XARoJK1l5bk+grtQG6MHMHzf32iONXGbmz7Hk+hbgxcFkzTJJ+OagDOrt+oPDzpoP0WHLGAwxBq4AHUI5rk5xIV3dj8o3d6wRhAXeLsrSYnGurKjviBd1UR31DXk9Ruj4nWDv8ltsLkf7DL/9H+JZa+FtL6zLAzZLgnxbOQF/YsiQ5LidbzSAgkQQbbfhMSQ8tDRnMHTL34O/UVyW5kKZZRb/bGoCZW1d6+Np0+ibdzRt5qX3lkDqK2f7ifDOIq3PmXwudo5BokcqbivWTmAxeClANpCCFxVnvh0sox3evGT7L+IJNtiWs+cDuPTJ5ggNApWCuB6p9tTlCKwZ6TGTSgKRg7TxtPZHZcolPawUDm4ilBPAccDNjPHXc8rBLdrhMRptKn4FZMFFUX69ljIV73i/aeQueRGEIK4JRQn0KQr7nZT6VupQ+r5JZn+Pz1OV/+yMhea4mmeBPqEGd4Xp6MzAd34rPuoeqFjTEAKzhHbrRYTj1Kw92/DVv/QExbfIG3mtrtiuBksE8rRh+QWL98Y4xsD9IphHS06K4tRbqabeocUP4GX2SWVQdO9Kqm4uv8UVyHdL5iQxPcteQCIDJ9tilgNJDASHTCsa+hBmPXYg95jGCnnsg3QQrcxzLca5I7WzG4jeQcoI=
  password:
    secure: JIzkR1rwgaysBxLr2syJERPJBi9sLoxki5k55YDsE1lmxaw8gYG8UBeqWWEWnv2VPKnLLBxxmuH8zT6wCvEy0v0UpwhlqlOWGKinpLdn7o6nNvKt9OK4d6hQTwmLj+aVg/WhdsTEWINEMA9N9IH12sNwrlRHhSwfz90nGJxHsMw1CE+pesvwcqngPoOMecJuX66esL5ll2wN5Mg9J5772G8ngDNUHU8zIFwtMxgepUEA4TrpPXv9/+iOmC71xjo+gntI21Rnz5eTmvyj9h9lXxtTcSkXJr1q3vMZv9XlnSK6bOT8HdDcAAp7l5lS/FvCwd4Wia+mBNwjZHxQQnBH39NnmwUKBCnbsoLq6zWU7qUs8w0aFLCICNApayoUIj82VCmyUlE6GqUymA529LTQ1wTRwuYs+Tdj1dhYTl4gd0N8P2txWSny6v3sbc0WXZRUOBkz9oy2jLoL/EvOpML42GOXkrEwSTYB64UnjDlHGzD70zRiQus05rYaN7/jwzTUnSGx7BcEppoxY40V1UpFl/PuabPdDtlA+NuK2Vqhd2DEQP5hx8teiSvxih/P+XEvZ9USnq5tJqUNabCsMPHhoHSTLd/dW1CoEuAD4IFbSCv3uDuAal26Qe6MWRlENQ9lZJSeSPiAlPxLPH4aJflUm13IMUMM29fbYX3pS+v6XYc=
  on:
    tags: true
    branch: master
after_success:
  - coveralls