version: "3"
services:
  django:
    image: django:dev
    build:
      context: ./django_app
    ports:
      - '8081:8080'
    environment:
      - DEBUG=false
    volumes:
      - ./django_app:/opt/app
    networks:
      backend:
        aliases:
          - django
  django-worker:
    image: django:dev
    ports:
      - '8085:8080'
    depends_on:
      - django
      - redis
    volumes:
      - ${TEST_PROJECT_PATH}/django_app:/opt/app
    networks:
      backend:
        aliases:
          - django-worker
  portainer:
    image: portainer/portainer
    ports:
      - "9100:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      backend:
        aliases:
          - portainer
  redis:
    image: redis:latest
    networks:
      backend:
        aliases:
          - redis
    ports:
      - "6380:6379"
  postgres:
    image: postgres:9.6
    volumes:
        - postgres-app-data:/var/lib/postgresql/data
    ports:
        - "5433:5432"
    networks:
      backend:
        aliases:
          - postgres
volumes:
  postgres-app-data:
networks:
  backend:
    driver: bridge