name: pre_commit
on: [ push ]
jobs:
  # Always Run.
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setups Python
        uses: actions/setup-python@v2
      - name: Run Pre-Commit
        uses: pre-commit/action@v2.0.0
